### Домашнее задание <a class="anchor" id="hw"></a><center>

In [2]:
import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm
import warnings
warnings.filterwarnings('ignore')

__Задача:__ подойдет ли репетитор для подготовки к экзамену по математике

In [3]:
X = np.array([ [   1,    1,  500,    1],
               [   1,    1,  700,    1],
               [   1,    2,  750,    2],
               [   1,    5,  600,    1],
               [   1,    3, 1450,    2],
               [   1,    0,  800,    1],
               [   1,    5, 1500,    3],
               [   1,   10, 2000,    3],
               [   1,    1,  450,    1],
               [   1,    2, 1000,    2]], dtype = np.float64)

y = np.array([0, 0, 1, 0, 1, 0, 1, 0, 1, 1])

In [4]:
def standard_scale(X):
    mean = X.mean(axis=0)
    std = X.std(axis=0)
    return (X - mean) / std

In [5]:
X_st = X.copy().astype(np.float64)
X_st[:, 1:4] = standard_scale(X_st[:, 1:4])
X_st

array([[ 1.        , -0.70710678, -0.97958969, -0.89625816],
       [ 1.        , -0.70710678, -0.56713087, -0.89625816],
       [ 1.        , -0.35355339, -0.46401617,  0.38411064],
       [ 1.        ,  0.70710678, -0.77336028, -0.89625816],
       [ 1.        ,  0.        ,  0.97958969,  0.38411064],
       [ 1.        , -1.06066017, -0.36090146, -0.89625816],
       [ 1.        ,  0.70710678,  1.08270439,  1.66447944],
       [ 1.        ,  2.47487373,  2.11385144,  1.66447944],
       [ 1.        , -0.70710678, -1.08270439, -0.89625816],
       [ 1.        , -0.35355339,  0.05155735,  0.38411064]])

**1. *Измените функцию calc_logloss так, чтобы нули по возможности не попадали в np.log.**

1 метод

In [6]:
def calc_logloss(y, y_pred):
    y_pred = np.where(y_pred == 1, 1 - 1e-8, y_pred)
    y_pred = np.where(y_pred == 0, 0 + 1e-8, y_pred)
    err = - np.mean(y * np.log(y_pred) + (1.0 - y) * np.log(1.0 - y_pred))
    return err

In [7]:
eps = 1e-8

np.clip([1, 0.5, 0], a_min=eps, a_max=1 - eps)

array([9.9999999e-01, 5.0000000e-01, 1.0000000e-08])

In [8]:
def calc_logloss(y, y_pred):
    eps = 1e-8
    y_pred = np.clip(y_pred, eps, 1 - eps)
    err = - np.mean(y * np.log(y_pred) + (1.0 - y) * np.log(1.0 - y_pred))
    return err

2 метод

In [9]:
def calc_logloss(y, y_pred):
    err = 0
    for i in range(len(y)):
        if y_pred[i] == 0:
            err += (1.0 - y[i]) * np.log(1.0 - y_pred[i])
        elif y_pred[i] == 1:
            err += y[i] * np.log(y_pred[i])
        else:
            err += y[i] * np.log(y_pred[i]) + (1.0 - y[i]) * np.log(1.0 - y_pred[i])
    return - err / len(y)

In [10]:
y1 = np.array([1, 0])
y_pred1 = np.array([0.9, 0])
calc_logloss(y1, y_pred1)

0.05268025782891314

In [11]:
y1 = np.array([1, 0])
y_pred1 = np.array([1, 0.1])
calc_logloss(y1, y_pred1)

0.05268025782891314

In [12]:
y1 = np.array([1, 0])
y_pred1 = np.array([0.9, 0.1])
calc_logloss(y1, y_pred1)

0.10536051565782628

**2. Подберите аргументы функции eval_model для логистической регрессии таким образом, чтобы log loss был минимальным.**

In [13]:
def sigmoid(z):
    res = 1 / (1 + np.exp(-z))
    return res

In [14]:
def eval_model(X, y, iterations, eta=1e-4):
    np.random.seed(42)
    W = np.random.randn(X.shape[1])
    n = X.shape[0]
    
    for i in range(iterations):
        z = np.dot(X, W)
        y_pred = sigmoid(z)
        err = calc_logloss(y, y_pred)
        
        dQ = 1/n * X.T @ (y_pred - y)
        W -= eta * dQ
        if i % (iterations / 10) == 0:
            print(i, W, err)
            
    final_error = calc_logloss(y, y_pred)
    return W, final_error

1 метод

аналог GridSearch

In [15]:
from tqdm import tqdm

In [16]:
np.logspace(2, 4, 4, dtype=np.int), np.linspace(1e-2, 5, 10)

(array([  100,   464,  2154, 10000]),
 array([0.01      , 0.56444444, 1.11888889, 1.67333333, 2.22777778,
        2.78222222, 3.33666667, 3.89111111, 4.44555556, 5.        ]))

In [17]:
iterations = np.logspace(2, 4, 4, dtype=np.int)
etas = np.linspace(1e-2, 5, 10)

best_error = np.inf
best_params = {}

for iteration in tqdm(iterations):
    for eta in etas:
        W, error = eval_model(X_st, y, iterations=iteration, eta=eta)
        if error < best_error:
            best_error = error
            best_params = {
                'iteration': iteration,
                'eta': eta
            }

print(f'Ошибка {best_error} при параметрах {best_params}')

  0%|          | 0/4 [00:00<?, ?it/s]

0 [ 0.49635916 -0.1409725   0.64535427  1.52178506] 0.760958797591889
10 [ 0.49265881 -0.16787071  0.62221328  1.50954192] 0.7467006818024327
20 [ 0.48868992 -0.19442917  0.59944411  1.49767566] 0.7328651153682048
30 [ 0.48446029 -0.22063955  0.57705409  1.48619252] 0.7194524935754576
40 [ 0.47997869 -0.24649338  0.55505065  1.4750986 ] 0.7064630339679188
50 [ 0.47525478 -0.27198192  0.53344129  1.46439984] 0.6938967869573868
60 [ 0.47029912 -0.29709626  0.51223358  1.45410204] 0.6817536325961876
70 [ 0.46512312 -0.32182725  0.49143512  1.44421083] 0.6700332616838688
80 [ 0.45973898 -0.34616556  0.47105359  1.4347317 ] 0.658735139989009
90 [ 0.45415964 -0.37010173  0.4510966   1.42566993] 0.6478584551577353
0 [ 0.47667685 -0.29112687  0.51593213  1.45276794] 0.760958797591889
10 [ 0.15302827 -1.07349673 -0.05330995  1.447242  ] 0.458878668542744
20 [ 0.0338664  -1.33389885 -0.1641304   1.79467485] 0.41846490870843844
30 [-2.07371606e-03 -1.53135455e+00 -2.56777284e-01  2.10047940e+00] 

 25%|██▌       | 1/4 [00:00<00:01,  2.86it/s]

70 [ 0.39579449 -3.29781006 -1.99822733  6.00510388] 0.2511399533730289
80 [ 0.46155658 -3.42789533 -2.17335216  6.35748839] 0.24474800454295043
90 [ 0.52457332 -3.55115244 -2.33750023  6.69013212] 0.2390663859588717
0 [ 0.37826527 -1.04189875 -0.13117859  1.10768234] 0.760958797591889
10 [-0.00618543 -2.0314492  -0.54660905  2.9407954 ] 0.3452925966686693
20 [ 0.06511937 -2.47646445 -0.95262246  3.88656217] 0.3043309289424501
30 [ 0.15385974 -2.76171976 -1.28483471  4.5779519 ] 0.2831549234360089
40 [ 0.24344915 -2.97992487 -1.5677191   5.14649003] 0.2690307681868176
50 [ 0.32969263 -3.16454021 -1.81664428  5.64274134] 0.25835000732224234
60 [ 0.41168091 -3.32988231 -2.04088394  6.09125239] 0.24967101192571062
70 [ 0.48948607 -3.48285308 -2.2464415   6.50558411] 0.24229411414025157
80 [ 0.56345441 -3.62708493 -2.43739097  6.89392971] 0.23583399933176627
90 [ 0.63397518 -3.76463807 -2.61659116  7.2615806 ] 0.23005861671400737
0 [ 0.35858295 -1.19205313 -0.26060073  1.03866522] 0.760958

 50%|█████     | 2/4 [00:00<00:01,  1.91it/s]

0 [ 0.31921832 -1.49236188 -0.51944502  0.90063097] 0.760958797591889
0 [ 0.49635916 -0.1409725   0.64535427  1.52178506] 0.760958797591889
0 [ 0.47667685 -0.29112687  0.51593213  1.45276794] 0.760958797591889
0 [ 0.45699453 -0.44128125  0.38650998  1.38375082] 0.760958797591889
0 [ 0.43731221 -0.59143562  0.25708784  1.3147337 ] 0.760958797591889
0 [ 0.4176299  -0.74159     0.1276657   1.24571658] 0.760958797591889
0 [ 0.39794758 -0.89174437 -0.00175644  1.17669946] 0.760958797591889
0 [ 0.37826527 -1.04189875 -0.13117859  1.10768234] 0.760958797591889
0 [ 0.35858295 -1.19205313 -0.26060073  1.03866522] 0.760958797591889
0 [ 0.33890064 -1.3422075  -0.39002287  0.96964809] 0.760958797591889
0 [ 0.31921832 -1.49236188 -0.51944502  0.90063097] 0.760958797591889


 75%|███████▌  | 3/4 [00:03<00:01,  1.49s/it]

0 [ 0.49635916 -0.1409725   0.64535427  1.52178506] 0.760958797591889
1000 [ 0.06528341 -1.25315687 -0.13031431  1.68209805] 0.42642421911106754
2000 [-0.00591593 -1.60120112 -0.2960273   2.21707777] 0.38196097010869967
3000 [-0.01097467 -1.85119187 -0.44498757  2.64578105] 0.3549927868836243
4000 [-2.64430856e-04 -2.04430387e+00 -5.82222091e-01  3.00431189e+00] 0.33646376256331906
5000 [ 0.01719932 -2.20052369 -0.70941905  3.31414696] 0.32274977674382266
6000 [ 0.03850056 -2.33129977 -0.82799326  3.58846186] 0.3120492881925758
7000 [ 0.06216276 -2.44374222 -0.93914508  3.83587188] 0.3033639688244948
8000 [ 0.08727955 -2.54253835 -1.04387339  4.06228822] 0.2960963045725309
9000 [ 0.11325547 -2.63091817 -1.14300269  4.27192266] 0.28986691616198357
0 [ 0.47667685 -0.29112687  0.51593213  1.45276794] 0.760958797591889
1000 [ 1.09439377 -4.68780498 -3.75952282  9.668002  ] 0.19782429297287785
2000 [ 1.8020679  -6.21006696 -5.53005669 13.51756994] 0.1605971865041851
3000 [ 2.29969558 -7.346

100%|██████████| 4/4 [00:16<00:00,  4.00s/it]

Ошибка 0.03424062515544959 при параметрах {'iteration': 10000, 'eta': 5.0}


2 метод

Вручную

In [18]:
W, error = eval_model(X_st, y, iterations=10000, eta=10)

0 [ 0.14172249 -2.84645945 -1.68657857  0.27823209] 0.760958797591889
1000 [  5.30333939 -14.52122924 -15.60570779  35.29706771] 0.07807940986335275
2000 [  7.02912602 -18.15641562 -21.49540915  46.86254822] 0.05947102607551209
3000 [  8.39021652 -20.87645288 -26.25647977  56.0061919 ] 0.0478778998649146
4000 [  9.52662466 -23.13755805 -30.23491759  63.63646683] 0.03981182658882034
5000 [ 10.49850422 -25.0739132  -33.63312141  70.1590696 ] 0.03392131553679026
6000 [ 11.34468769 -26.76262736 -36.58830102  75.83612081] 0.029461093292982687
7000 [ 12.09220329 -28.25653157 -39.1963586   80.84986745] 0.025983447619334722
8000 [ 12.76053153 -29.59371813 -41.52630223  85.33153884] 0.02320548950630342
9000 [ 13.36409782 -30.80247173 -43.62911967  89.3782373 ] 0.020941064671621414


**3. Создайте функцию calc_pred_proba, возвращающую предсказанную вероятность класса 1 (на вход подаются W, который уже посчитан функцией eval_model и X, на выходе - массив y_pred_proba).**

In [19]:
def calc_pred_proba(W, X):
    y_pred_proba = sigmoid(np.dot(X, W))
    return y_pred_proba

In [20]:
calc_pred_proba(W, X_st)

array([8.93627716e-02, 6.82367011e-10, 1.00000000e+00, 2.08171530e-25,
       9.93610002e-01, 4.50551813e-09, 1.00000000e+00, 1.63447642e-03,
       9.14866911e-01, 1.00000000e+00])

**4. Создайте функцию calc_pred, возвращающую предсказанный класс (на вход подаются W, который уже посчитан функцией eval_model и X, на выходе - массив y_pred).**

In [21]:
def calc_pred(W, X):
    y_pred_proba = calc_pred_proba(W, X)
    y_pred = np.where(y_pred_proba > 0.5, 1, 0)
    return y_pred

In [22]:
pred = calc_pred(W, X_st)
pred

array([0, 0, 1, 0, 1, 0, 1, 0, 1, 1])

**5. *Реализуйте функции для подсчета Accuracy, матрицы ошибок, точности и полноты, а также F1 score.**

Accuracy

In [23]:
def accuracy(y, y_pred):
    accuracy = np.mean(y == y_pred)
    return accuracy

In [24]:
print(f'True \t  {y}')
print(f'Predicted {pred}')

True 	  [0 0 1 0 1 0 1 0 1 1]
Predicted [0 0 1 0 1 0 1 0 1 1]


In [25]:
accuracy(y, pred)

1.0

Confusion Matrix

In [ ]:
# TP  FP
# FN  TN

In [26]:
def confusion_matrix(y, y_pred):
    cm = np.zeros((2, 2))
    for i in range(len(y)): 
        if y[i] == y_pred[i] == 1: # TP
            cm[0][0] += 1
        elif y[i] == y_pred[i] == 0: # TN
            cm[1][1] += 1
        elif y[i] != y_pred[i] and y[i] == 1: # FN
            cm[1][0] += 1
        elif y[i] != y_pred[i] and y[i] == 0: # FP
            cm[0][1] += 1
    return cm

In [27]:
cm = confusion_matrix(y, pred)
cm

array([[5., 0.],
       [0., 5.]])

Precision

In [28]:
def precision(y, y_pred):
    cm = confusion_matrix(y, y_pred)
    TP = cm[0][0]
    TN = cm[1][1]
    FP = cm[0][1]
    FN = cm[1][0]
    precision = TP / (TP + FP)
    return precision

In [29]:
precision(y, pred)

1.0

Recall

In [30]:
def recall(y, y_pred):
    cm = confusion_matrix(y, y_pred)
    TP = cm[0][0]
    TN = cm[1][1]
    FP = cm[0][1]
    FN = cm[1][0]
    recall = TP / (TP + FN)
    return recall

In [31]:
recall(y, pred)

1.0

F-score

In [32]:
def f_score(y, y_pred):
    pr = precision(y, y_pred)
    rec = recall(y, y_pred)
    f_score = 2 * pr * rec / (pr + rec)
    return f_score

In [33]:
f_score(y, pred)

1.0

In [34]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix


print(f'accuracy {accuracy_score(y, pred)}')
print(f'precision {precision_score(y, pred)}')
print(f'recall {recall_score(y, pred)}')
print(f'f-score {f1_score(y, pred)}')
print(f'\n {confusion_matrix(y, pred)}')

accuracy 1.0
precision 1.0
recall 1.0
f-score 1.0

 [[5 0]
 [0 5]]


**6. Могла ли модель переобучиться? Почему?**

Могла, если взять большое количество итераций, когда ошибка будет стремиться к нулю.